name: Unit test
run-name: Unit test

on:
  push:
    branches:
      - '**'

jobs:
  unit-tests:
    name: 'Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Go'
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: 'Setup cluster'
        uses: helm/kind-action@v1

      - name: 'Set up Kubernetes Test Data'
        run: make setup-test-data

      - name: 'Build and Test'
        env:
          TEST_FLAGS: '-v'
        run: make mod-tidy test

      - name: 'Clean up Kubernetes Test Data'
        if: always() # Ensures it runs even if tests fail
        run: make teardown-test-data